### ISSUE TITLE
File extension is incorrect

### ISSUE THREAD

**Issue by masonhuemmer** [tailscale/gitops-acl-action#13]
I am wondering why the enxtension is **.hujson** instead of **.json**. 
https://github.com/tailscale/gitops-acl-action/blob/f276492f391dbac231b24c9e01a64a441264b3d6/action.yml#L13

**Comment by DentonGentry** [comment]
It isn't exactly JSON, it allows C-style comments and trailing commas in lists.
https://github.com/tailscale/hujson/

**Comment by masonhuemmer** [comment]
Looks like the extension is "Json for Humans". Closing ticket now.
