### ISSUE TITLE
Please verify this action in the GitHub Marketplace

### ISSUE THREAD

**Issue by mtrimarchi** [tailscale/gitops-acl-action#9]
We have in place a security enforcement policy about external Actions.

![image](https://user-images.githubusercontent.com/16150965/194366312-a8fe2ca4-d240-4c85-9388-2538d25daae6.png)

This is the error we get running the Action:

`tailscale/gitops-acl-action@v1 is not allowed to be used in <REDACTED>. Actions in this workflow must be: within a repository owned by <REDACTED>, created by GitHub, or verified in the GitHub Marketplace.`

**Comment by DentonGentry** [comment]
We have completed GitHub Publisher Verification for the Tailscale organization.
Please reopen if there is more that needs to be done.
